spring.application.name=SpringBootPractical

# Server Configuration (Section 11.6)
server.port=8081

# Database Configuration (Section 11.3 Auto-Configuration)
spring.datasource.url=jdbc:mysql://localhost:3306/spring_boot_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true

# Custom Property (Section 11.5)
app.message=Welcome to Anuj's Spring Boot App!